"use client";

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './navbar'
import { useState } from 'react';
import { usePathname } from 'next/navigation';
import { SessionProvider } from 'next-auth/react';

const disabledNavbar = ['/login', '/register'];

const inter = Inter({ subsets: ['latin'] })
// enable below code, it just for layout-template testing
// export const metadata: Metadata = {
  //   title: 'Create Next App',
  //   description: 'Generated by create next app',
  // }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
  const pathName = usePathname();
  // const [state, setState] = useState(0);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {!disabledNavbar.includes(pathName) && <Navbar/>}
        {/* <div>Layout: {state}</div> */}
        {/* <button onClick={() => setState(state+1)}>Click</button> */}
        {children}
        </SessionProvider>
        </body>
    </html>
  )
}
